#!/usr/bin/env node
/**
 * Generate `src/generated/index.ts` from the desktop's embedded control icons
 * (`crates/ui/assets/icons/*.svg`) — the same assets `crates/ui/src/icons.rs`
 * compiles in. Parity is by construction: the web client never hand-draws a
 * glyph the desktop does not have, and a changed asset changes both clients.
 *
 *   node scripts/generate.mjs            # write
 *   node scripts/generate.mjs --check    # fail when stale (no CI gate runs
 *                                         # this — regeneration is manual)
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "../../../..");
const assetDir = join(repoRoot, "crates/ui/assets/icons");
const outDir = join(here, "../src/generated");
const outFile = join(outDir, "index.ts");

/** `alt-arrow-down.svg` -> `altArrowDown`. */
const camel = (name) => name.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());

/** Pull the root `<svg …>` attributes and its inner markup. */
function parse(source) {
  const open = source.match(/<svg\b([^>]*)>/);
  if (!open) {
    throw new Error("no <svg> root");
  }
  const attrs = Object.fromEntries(
    [...open[1].matchAll(/([a-zA-Z:-]+)\s*=\s*"([^"]*)"/g)].map((m) => [m[1], m[2]]),
  );
  const body = source
    .slice(open.index + open[0].length, source.lastIndexOf("</svg>"))
    .replace(/\s+/g, " ")
    .trim();
  return { viewBox: attrs.viewBox ?? "0 0 24 24", fill: attrs.fill ?? "none", body };
}

const entries = readdirSync(assetDir)
  .filter((file) => file.endsWith(".svg"))
  .sort()
  .map((file) => {
    const slug = file.slice(0, -4);
    const { viewBox, fill, body } = parse(readFileSync(join(assetDir, file), "utf8"));
    return { key: camel(slug), slug, viewBox, fill, body };
  });

const lines = [
  "// @generated by web/packages/icons/scripts/generate.mjs — do not edit.",
  "// Source: crates/ui/assets/icons/*.svg (the assets crates/ui/src/icons.rs embeds).",
  "",
  "export interface IconAsset {",
  "  /** Root `viewBox`, verbatim from the asset. */",
  "  readonly viewBox: string;",
  "  /** Root `fill`, verbatim — `none` for stroked Solar glyphs. */",
  "  readonly fill: string;",
  "  /** Inner markup; every paint is `currentColor`, so the glyph tints with `color`. */",
  "  readonly body: string;",
  "}",
  "",
  "export const iconAssets = {",
  ...entries.map(
    (e) =>
      `  ${e.key}: { viewBox: ${JSON.stringify(e.viewBox)}, fill: ${JSON.stringify(e.fill)}, body: ${JSON.stringify(e.body)} },`,
  ),
  "} as const satisfies Record<string, IconAsset>;",
  "",
  "export type IconName = keyof typeof iconAssets;",
  "",
];
const next = lines.join("\n");

if (process.argv.includes("--check")) {
  const current = existsSync(outFile) ? readFileSync(outFile, "utf8") : "";
  if (current !== next) {
    console.error(
      "@roboco/icons is stale — run `pnpm --filter @roboco/icons regenerate` and commit the result.",
    );
    process.exit(1);
  }
  console.log(`@roboco/icons is fresh (${entries.length} glyphs).`);
} else {
  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, next);
  console.log(`wrote ${outFile} (${entries.length} glyphs)`);
}
