//! wiregen — generates the web client's TypeScript wire types
//! (`web/packages/proto/src/generated/`) from the Rust wire crates
//! (`roboco-proto`, `roboco-doc`, `roboco-engine`, `roboco-update`) via ts-rs.
//!
//! - `cargo run -p wiregen` — regenerate in place.
//! - `cargo run -p wiregen -- --check` — regenerate into a temp dir and fail on
//!   any diff against the checked-in output (the CI freshness gate: a Rust wire
//!   change without regeneration is a red build).
//!
//! Serde naming carries over exactly (camelCase fields, kebab-case/lowercase
//! fieldless enums, internally tagged enums, the untagged `TranscriptFrame`) —
//! the derives only ADD `ts_rs::TS`; they must never change serde output (the
//! existing serde contract tests in the wire crates pin that). The few
//! untyped/dynamic fields (`modelOptions`, `ToolCall::Mcp/Unknown.input`,
//! ad-hoc `json!` replies) are hand-written in `web/packages/proto/src/shims.ts`.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
    process::ExitCode,
};

use anyhow::{Context, Result};
use ts_rs::{Config, TS};

/// Header stamped on every generated file.
const HEADER: &str =
    "// DO NOT EDIT — generated by wiregen (`cargo run -p wiregen`; gate: `-- --check`).";

/// The ts-rs header line, replaced by [`HEADER`].
const TS_RS_HEADER: &str = "// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.";

/// Legacy wire names that collide with the canonical glossary (ADR 0005: wire
/// names are frozen, so the generated TS keeps the legacy spelling and gets
/// this note pointing at CONTEXT.md). Keyed by generated file stem.
const LEGACY_NOTES: &[(&str, &str)] = &[
    (
        "Session",
        "Legacy wire name (ADR 0005): the canonical term is \"Chat status\" — see CONTEXT.md.",
    ),
    (
        "SessionStatus",
        "Legacy wire name (ADR 0005): the canonical term is \"Chat status\" — see CONTEXT.md.",
    ),
    (
        "SessionMessageEntry",
        "Legacy wire name (ADR 0005): the chat doc family — canonical terms are \"Chat doc\" / \"transcript entry\" — see CONTEXT.md.",
    ),
    (
        "SessionTail",
        "Legacy wire name (ADR 0005): the chat doc family — canonical term is \"Chat doc\" — see CONTEXT.md.",
    ),
    (
        "SessionCommandEntry",
        "Legacy wire name (ADR 0005): the chat doc family — canonical term is \"Chat doc\" — see CONTEXT.md.",
    ),
    (
        "SessionCommandKind",
        "Legacy wire name (ADR 0005): the chat doc family — canonical term is \"Chat doc\" — see CONTEXT.md.",
    ),
    (
        "SessionCommandStatus",
        "Legacy wire name (ADR 0005): the chat doc family — canonical term is \"Chat doc\" — see CONTEXT.md.",
    ),
    (
        "SessionCommandPayload",
        "Legacy wire name (ADR 0005): the chat doc family — canonical term is \"Chat doc\" — see CONTEXT.md.",
    ),
    (
        "TerminalSession",
        "Legacy wire name (ADR 0005): the canonical term is \"Terminal\" — see CONTEXT.md.",
    ),
    (
        "AgentAccount",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentAccountsSnapshot",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentAccountWarning",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentLoginStart",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentLoginMode",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentLoginPoll",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "AgentLoginStatus",
        "Legacy wire name (ADR 0005): the canonical term is \"Harness account\" — see CONTEXT.md.",
    ),
    (
        "WorkspaceScope",
        "Legacy wire name (ADR 0005): the engine data scope; \"Workspace\" is an avoided word for the registry — see CONTEXT.md.",
    ),
    (
        "Chat",
        "Field `roomGen` is a legacy wire name (ADR 0005): tolerate it, never build on it — see CONTEXT.md.",
    ),
];

/// Every wire-crossing type, grouped by owning crate. This list IS the wire
/// surface manifest: add a type here when it starts crossing the RPC/HTTP
/// boundary. (`export_all` also pulls in each type's named dependencies.)
fn export_all(cfg: &Config) -> Result<()> {
    macro_rules! export {
        ($($t:ty),* $(,)?) => {
            $( <$t as TS>::export_all(cfg).context(concat!("export ", stringify!($t)))?; )*
        };
    }

    // roboco-proto: entity rows, harness/agent types, remote access, previews.
    export!(
        // entities.rs
        roboco_proto::Device,
        roboco_proto::Space,
        roboco_proto::ChatConfig,
        roboco_proto::ConversationSourceContext,
        roboco_proto::Chat,
        roboco_proto::ChatIndicator,
        roboco_proto::SessionStatus,
        roboco_proto::Session,
        roboco_proto::Repo,
        roboco_proto::RepoRef,
        roboco_proto::GitHistoryRefKind,
        roboco_proto::GitHistoryRef,
        roboco_proto::GitHistoryCommit,
        roboco_proto::GitHistoryComparison,
        roboco_proto::GitHistoryPage,
        roboco_proto::Worktree,
        roboco_proto::FolderEntry,
        roboco_proto::FolderListing,
        roboco_proto::DriveEntry,
        roboco_proto::DriveListing,
        roboco_proto::FileSearchMatch,
        roboco_proto::WorkspaceTarget,
        roboco_proto::ListWorkspaceDirectoryRequest,
        roboco_proto::WorkspaceDirectoryPage,
        roboco_proto::WorkspaceEntry,
        roboco_proto::WorkspaceEntryKind,
        roboco_proto::SearchWorkspaceFilesRequest,
        roboco_proto::WorkspaceFileSearchMatch,
        roboco_proto::ReadWorkspaceFileRequest,
        roboco_proto::ReadWorkspaceImageRequest,
        roboco_proto::WorkspaceImageChunk,
        roboco_proto::WorkspaceFileText,
        roboco_proto::WorkspaceTextEncoding,
        roboco_proto::WorkspaceLineEnding,
        roboco_proto::WorkspaceReadOnlyReason,
        roboco_proto::WriteWorkspaceFileRequest,
        roboco_proto::WorkspaceWritableEncoding,
        roboco_proto::WorkspaceWritableLineEnding,
        roboco_proto::WriteWorkspaceFileOutcome,
        roboco_proto::WorkspaceFileWriteResult,
        roboco_proto::WorkspaceFileConflictReason,
        roboco_proto::WatchWorkspaceFilesRequest,
        roboco_proto::WorkspaceFileChanges,
        roboco_proto::WorkspaceFileChange,
        roboco_proto::WorkspaceFileChangeKind,
        roboco_proto::DiffFileSummary,
        roboco_proto::CheckoutDiff,
        roboco_proto::GitFileState,
        roboco_proto::GitFileStatus,
        roboco_proto::CheckoutGitStatus,
        roboco_proto::WorkspaceGitStatusFrame,
        roboco_proto::ChangeRequestState,
        roboco_proto::ChangeRequestSummary,
        roboco_proto::CheckoutChangeRequestStatus,
        roboco_proto::GetCheckoutFileDiffTextRequest,
        roboco_proto::CheckoutFileDiffText,
        roboco_proto::DiscardWorkingTreeRequest,
        roboco_proto::DiscardWorkingTreeOutcome,
        roboco_proto::AgentAccount,
        roboco_proto::AgentAuthKind,
        roboco_proto::AgentAccountsSnapshot,
        roboco_proto::AgentAccountWarning,
        roboco_proto::AgentLoginStart,
        roboco_proto::AgentLoginMode,
        roboco_proto::AgentLoginPoll,
        roboco_proto::AgentLoginStatus,
        roboco_proto::AgentUsageWindow,
        roboco_proto::ProjectActionIcon,
        roboco_proto::ProjectAction,
        roboco_proto::ProjectActionDraft,
        roboco_proto::ProjectActionsSnapshot,
        roboco_proto::ProjectActionRun,
        roboco_proto::SidebarSection,
        roboco_proto::SidebarStateSnapshot,
        roboco_proto::CreateWorktreeOutcome,
        roboco_proto::TerminalSession,
        roboco_proto::TerminalEvent,
        roboco_proto::TransferProgress,
        roboco_proto::Connectivity,
        roboco_proto::ConnectivityState,
        roboco_proto::ChatConnectivity,
        // agent.rs
        roboco_proto::HarnessId,
        roboco_proto::ReasoningLevel,
        roboco_proto::SandboxLevel,
        roboco_proto::SteeringMode,
        roboco_proto::Model,
        roboco_proto::ModelOption,
        roboco_proto::ModelOptionChoice,
        roboco_proto::RunRequest,
        roboco_proto::WorktreeSpec,
        roboco_proto::ToolCall,
        roboco_proto::TodoItem,
        roboco_proto::SlashCommand,
        roboco_proto::ToolDiff,
        roboco_proto::UserInputQuestion,
        roboco_proto::UserInputAnswer,
        roboco_proto::DoneStatus,
        roboco_proto::AgentEvent,
        roboco_proto::ContextUsage,
        // remote.rs
        roboco_proto::RemoteAccessStatus,
        roboco_proto::PairedSession,
        roboco_proto::RemoteAccessSnapshot,
        roboco_proto::PairingLink,
        // workspace.rs
        roboco_proto::WorkspaceScope,
        roboco_proto::EngineInfo,
        // preview.rs
        roboco_proto::PreviewService,
        roboco_proto::PreviewSnapshot,
        roboco_proto::WatchPreviewsParams,
    );

    // roboco-doc: transcript entries/parts, the command ledger, the queue,
    // and the WatchDocMessages delta frames.
    export!(
        roboco_doc::MessageRole,
        roboco_doc::SessionMessageEntry,
        roboco_doc::SessionTail,
        roboco_doc::ToolDiffStat,
        roboco_doc::MessageStatus,
        roboco_doc::SubagentStatus,
        roboco_doc::MessagePart,
        roboco_doc::SessionCommandKind,
        roboco_doc::SessionCommandStatus,
        roboco_doc::SessionCommandPayload,
        roboco_doc::CommandBasedOn,
        roboco_doc::SessionCommandEntry,
        roboco_doc::QueuedMessage,
        roboco_doc::QueueDeliveryGate,
        roboco_doc::TranscriptUpdate,
        roboco_doc::TranscriptBaseline,
        roboco_doc::TranscriptFrame,
        roboco_doc::TranscriptUpsert,
        roboco_doc::TextAppend,
    );

    // roboco-engine: the wire types that live outside proto (harness catalog,
    // uploads, queue-edit lease outcomes, pairing grant, the Mutate params).
    export!(
        roboco_engine::registry::HarnessDescriptor,
        roboco_engine::registry::TitleSettings,
        roboco_engine::uploads::AttachmentChunk,
        roboco_engine::uploads::AttachmentTransfer,
        roboco_engine::doc_host::BeginQueueEditOutcome,
        roboco_engine::doc_host::RenewQueueEditOutcome,
        roboco_engine::doc_host::FinishQueueEditOutcome,
        roboco_engine::rpc::FinishQueuedMessageEditAction,
        roboco_engine::rpc::MutateParams,
        roboco_engine::pairing::SessionGrant,
    );

    // roboco-update: the UpdateStatus stream item.
    export!(roboco_update::UpdateStatus);

    Ok(())
}

/// Wire-protocol constants the web client shares with the engine (capability
/// strings gate feature degradation; chunk sizes bound transfer loops).
fn constants_ts() -> String {
    use roboco_proto::capabilities;
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("\n\n");
    out.push_str(
        "/** Protocol feature strings advertised in `EngineInfo.capabilities` / `Device.capabilities`. */\n",
    );
    out.push_str(&format!(
        "export const MESSAGE_QUEUE_V1 = {:?};\n",
        capabilities::MESSAGE_QUEUE_V1
    ));
    out.push_str(&format!(
        "export const MESSAGE_QUEUE_ACTIONS_V1 = {:?};\n",
        capabilities::MESSAGE_QUEUE_ACTIONS_V1
    ));
    out.push_str(&format!(
        "export const MESSAGE_QUEUE_ATTACHMENTS_V1 = {:?};\n",
        capabilities::MESSAGE_QUEUE_ATTACHMENTS_V1
    ));
    out.push_str(&format!(
        "export const MESSAGE_QUEUE_CLEAN_ATTACHMENT_TEXT_V1 = {:?};\n",
        capabilities::MESSAGE_QUEUE_CLEAN_ATTACHMENT_TEXT_V1
    ));
    out.push_str(&format!(
        "export const MESSAGE_QUEUE_EDIT_LEASE_V1 = {:?};\n",
        capabilities::MESSAGE_QUEUE_EDIT_LEASE_V1
    ));
    out.push_str("\n/** Every capability this build of the engine advertises. */\n");
    let current: Vec<String> = capabilities::CURRENT
        .iter()
        .map(|c| format!("{c:?}"))
        .collect();
    out.push_str(&format!(
        "export const CAPABILITIES_CURRENT: readonly string[] = [{}];\n",
        current.join(", ")
    ));
    out.push_str(&format!(
        "\nexport const PREVIEW_PROXY_PORT = {};\n",
        roboco_proto::PREVIEW_PROXY_PORT
    ));
    out.push_str(&format!(
        "export const MAX_WORKSPACE_IMAGE_BYTES = {};\n",
        roboco_proto::MAX_WORKSPACE_IMAGE_BYTES
    ));
    out.push_str(&format!(
        "export const WORKSPACE_IMAGE_CHUNK_BYTES = {};\n",
        roboco_proto::WORKSPACE_IMAGE_CHUNK_BYTES
    ));
    out.push_str(&format!(
        "\n/** Session-scoped id of the live plan/todo chip (ACP plan updates carry no wire id). */\n\
         export const LIVE_PLAN_TOOL_ID = {:?};\n",
        roboco_proto::LIVE_PLAN_TOOL_ID
    ));
    let model_keys: Vec<String> = roboco_proto::SUBAGENT_MODEL_KEYS
        .iter()
        .map(|c| format!("{c:?}"))
        .collect();
    out.push_str(&format!(
        "\n/** Spawn-input keys that carry a child model, in precedence order. */\n\
         export const SUBAGENT_MODEL_KEYS: readonly string[] = [{}];\n",
        model_keys.join(", ")
    ));
    let input_keep: Vec<String> = roboco_proto::SUBAGENT_INPUT_KEEP
        .iter()
        .map(|c| format!("{c:?}"))
        .collect();
    out.push_str(&format!(
        "\n/** The only spawn-input keys preserved in a doc-side tool call. */\n\
         export const SUBAGENT_INPUT_KEEP: readonly string[] = [{}];\n",
        input_keep.join(", ")
    ));
    out
}

/// Replace the ts-rs header with ours and annotate legacy wire names.
fn postprocess(dir: &Path) -> Result<BTreeMap<String, String>> {
    let mut files = BTreeMap::new();
    for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
        let entry = entry?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("ts") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_string();
        let content =
            fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let body = content
            .strip_prefix(TS_RS_HEADER)
            .map(|rest| rest.trim_start_matches(['\r', '\n']))
            .unwrap_or(&content);
        let mut out = String::from(HEADER);
        out.push('\n');
        if let Some(note) = LEGACY_NOTES
            .iter()
            .find(|(name, _)| *name == stem)
            .map(|(_, note)| *note)
        {
            out.push_str("// ");
            out.push_str(note);
            out.push('\n');
        }
        out.push('\n');
        out.push_str(body);
        files.insert(stem, out);
    }
    Ok(files)
}

fn generate(dir: &Path) -> Result<()> {
    if dir.exists() {
        fs::remove_dir_all(dir).with_context(|| format!("clean {}", dir.display()))?;
    }
    fs::create_dir_all(dir).with_context(|| format!("create {}", dir.display()))?;

    // JSON numbers, not bigints: no wire field exceeds 2^53 (epoch millis,
    // byte counts). Extensionless imports match the workspace's bundler
    // module resolution.
    let cfg = Config::new()
        .with_out_dir(dir)
        .with_large_int("number")
        .with_import_extension(None::<String>);
    export_all(&cfg)?;

    let mut files = postprocess(dir)?;
    files.insert("constants".to_string(), constants_ts());

    let mut index = String::from(HEADER);
    index.push_str("\n\n");
    for name in files.keys() {
        index.push_str(&format!("export * from \"./{name}\";\n"));
    }
    files.insert("index".to_string(), index);

    for (stem, content) in &files {
        fs::write(dir.join(format!("{stem}.ts")), content)
            .with_context(|| format!("write {stem}.ts"))?;
    }
    Ok(())
}

/// Snapshot a directory of generated files as `relpath -> bytes`.
fn snapshot(dir: &Path) -> Result<BTreeMap<String, Vec<u8>>> {
    let mut files = BTreeMap::new();
    if !dir.exists() {
        return Ok(files);
    }
    for entry in fs::read_dir(dir).with_context(|| format!("read {}", dir.display()))? {
        let path = entry?.path();
        if path.is_file() {
            let name = path
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or_default()
                .to_string();
            files.insert(name, fs::read(&path)?);
        }
    }
    Ok(files)
}

fn check(real: &Path) -> Result<bool> {
    let tmp = tempfile::tempdir().context("create temp dir")?;
    let fresh = tmp.path().join("generated");
    generate(&fresh)?;

    let expected = snapshot(&fresh)?;
    let actual = snapshot(real)?;
    let mut stale: Vec<String> = Vec::new();
    for (name, bytes) in &expected {
        match actual.get(name) {
            None => stale.push(format!("{name}: missing (not generated)")),
            Some(actual) if actual != bytes => stale.push(format!("{name}: differs")),
            Some(_) => {}
        }
    }
    for name in actual.keys() {
        if !expected.contains_key(name) {
            stale.push(format!("{name}: leftover (no longer generated)"));
        }
    }
    if stale.is_empty() {
        return Ok(true);
    }
    eprintln!(
        "wire types are stale — regenerate with `cargo run -p wiregen`:\n  {}",
        stale.join("\n  ")
    );
    Ok(false)
}

fn main() -> ExitCode {
    let check_mode = std::env::args().any(|arg| arg == "--check");
    let unknown: Vec<String> = std::env::args()
        .skip(1)
        .filter(|arg| arg != "--check")
        .collect();
    if !unknown.is_empty() {
        eprintln!("usage: wiregen [--check]");
        return ExitCode::FAILURE;
    }

    let out_dir =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../web/packages/proto/src/generated");
    if check_mode {
        return match check(&out_dir) {
            Ok(true) => {
                println!("wire types are fresh ({}).", out_dir.display());
                ExitCode::SUCCESS
            }
            Ok(false) => ExitCode::FAILURE,
            Err(err) => {
                eprintln!("wiregen: {err:#}");
                ExitCode::FAILURE
            }
        };
    }
    match generate(&out_dir) {
        Ok(()) => {
            println!("generated {}", out_dir.display());
            ExitCode::SUCCESS
        }
        Err(err) => {
            eprintln!("wiregen: {err:#}");
            ExitCode::FAILURE
        }
    }
}
